### ISSUE TITLE
"Download records" fails

### ISSUE THREAD

**Issue by ozankececioglu** [diki/surflog#1]
app.entry.js:3355 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `ManageRecords`. See https://fb.me/react-warning-keys for more information.
    in li (created by ManageRecords)
    in ManageRecords (created by Stage)
    in main (created by Stage)
    in Stage (created by App)
    in main (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in Provider

**Comment by diki** [comment]
Download bug fixed, cheers!

P.S. also added last visits listing on main window ;)
